import type {
  Additive,
  BaseOil,
  DashboardSummary,
  Experiment,
  Formulation,
  Molecule,
  MoleculeDescriptor,
  PerformanceResult
} from "../types";

const now = "2026-06-18T12:00:00.000Z";

export const mockSvg = (label: string) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="420" height="240" viewBox="0 0 420 240"><rect width="420" height="240" rx="6" fill="#f8fafc"/><path d="M80 128 L150 88 L220 128 L290 88 L350 126" stroke="#0f766e" stroke-width="8" fill="none" stroke-linecap="round" stroke-linejoin="round"/><circle cx="80" cy="128" r="18" fill="#2563eb"/><circle cx="150" cy="88" r="18" fill="#14b8a6"/><circle cx="220" cy="128" r="18" fill="#f59e0b"/><circle cx="290" cy="88" r="18" fill="#ef4444"/><circle cx="350" cy="126" r="18" fill="#64748b"/><text x="210" y="206" text-anchor="middle" font-family="Arial" font-size="18" fill="#172033">${label}</text></svg>`;

export const molecules: Molecule[] = [
  {
    id: "mol-001",
    name: "正十六烷",
    aliases: "十六烷",
    smilesRaw: "CCCCCCCCCCCCCCCC",
    smilesCanonical: "CCCCCCCCCCCCCCCC",
    inchi: "InChI=1S/C16H34/c1-3-5-7-9-11-13-15-16-14-12-10-8-6-4-2/h3-16H2,1-2H3",
    inchiKey: "DCAYPVUWAIABOU-UHFFFAOYSA-N",
    formula: "C16H34",
    molecularWeight: 226.448,
    category: "base_oil_representative",
    additiveFunctionTags: [],
    structureSvgPath: "files/structures/mol-001.svg",
    structureSvg: mockSvg("正十六烷"),
    molFilePath: "files/structures/mol-001.mol",
    sdfFilePath: "files/structures/mol-001.sdf",
    pdbFilePath: "",
    sdfBlock: "正十六烷\n  LMD 模拟\n\n  0  0  0  0  0  0            999 V2000\nM  END\n$$$$",
    rdkitDescriptorStatus: "calculated",
    mordredDescriptorStatus: "calculated",
    descriptorReady: true,
    sourceId: "src-001",
    dataSource: "模拟文献",
    notes: "线性烃类基础油代表分子。",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "mol-002",
    name: "PAO 代表分子",
    aliases: "氢化聚α烯烃片段",
    smilesRaw: "CC(C)CCCC(C)CCCC",
    smilesCanonical: "CC(C)CCCC(C)CCCC",
    inchi: "mock:InChI:PAO",
    inchiKey: "PAOREPRESENTATIVE",
    formula: "C13H28",
    molecularWeight: 184.37,
    category: "base_oil_representative",
    additiveFunctionTags: [],
    structureSvgPath: "files/structures/mol-002.svg",
    structureSvg: mockSvg("PAO 代表分子"),
    molFilePath: "",
    sdfFilePath: "",
    pdbFilePath: "",
    rdkitDescriptorStatus: "calculated",
    mordredDescriptorStatus: "mock",
    descriptorReady: true,
    sourceId: "src-001",
    dataSource: "内部模拟数据",
    notes: "PAO 基础油的模拟代表分子。",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "mol-003",
    name: "类 ZDDP 添加剂",
    aliases: "二烷基二硫代磷酸锌模拟物",
    smilesRaw: "CCOP(=S)(S[Zn]SP(=S)(OCC)OCC)OCC",
    smilesCanonical: "CCOP(=S)(S[Zn]SP(=S)(OCC)OCC)OCC",
    inchi: "mock:InChI:ZDDP",
    inchiKey: "ZDDPLIKEADDITIVE",
    formula: "C8H20O4P2S4Zn",
    molecularWeight: 419.86,
    category: "additive",
    additiveFunctionTags: ["antiwear", "extreme_pressure"],
    structureSvgPath: "files/structures/mol-003.svg",
    structureSvg: mockSvg("类 ZDDP 添加剂"),
    molFilePath: "",
    sdfFilePath: "",
    pdbFilePath: "",
    rdkitDescriptorStatus: "calculated",
    mordredDescriptorStatus: "calculated",
    descriptorReady: true,
    sourceId: "src-002",
    dataSource: "模拟添加剂数据集",
    notes: "含 Zn、P、S 元素，用于抗磨膜形成。",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "mol-004",
    name: "磷酸酯添加剂",
    aliases: "三芳基磷酸酯模拟物",
    smilesRaw: "O=P(Oc1ccccc1)(Oc1ccccc1)Oc1ccccc1",
    smilesCanonical: "O=P(Oc1ccccc1)(Oc1ccccc1)Oc1ccccc1",
    inchi: "mock:InChI:PhosphateEster",
    inchiKey: "PHOSPHATEESTERMOCK",
    formula: "C18H15O4P",
    molecularWeight: 326.29,
    category: "additive",
    additiveFunctionTags: ["antiwear", "friction_modifier"],
    structureSvgPath: "files/structures/mol-004.svg",
    structureSvg: mockSvg("磷酸酯"),
    molFilePath: "",
    sdfFilePath: "",
    pdbFilePath: "",
    rdkitDescriptorStatus: "calculated",
    mordredDescriptorStatus: "failed",
    descriptorReady: false,
    sourceId: "src-003",
    dataSource: "模拟筛选",
    notes: "模拟数据中有意设置 Mordred 失败，用于验证描述符中心。",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "mol-005",
    name: "胺类抗氧剂",
    aliases: "类二苯胺抗氧剂",
    smilesRaw: "c1ccc(Nc2ccccc2)cc1",
    smilesCanonical: "c1ccc(Nc2ccccc2)cc1",
    inchi: "mock:InChI:AmineAntioxidant",
    inchiKey: "AMINEANTIOXIDANT",
    formula: "C12H11N",
    molecularWeight: 169.23,
    category: "additive",
    additiveFunctionTags: ["antioxidant"],
    structureSvgPath: "files/structures/mol-005.svg",
    structureSvg: mockSvg("胺类抗氧剂"),
    molFilePath: "",
    sdfFilePath: "",
    pdbFilePath: "",
    rdkitDescriptorStatus: "pending",
    mordredDescriptorStatus: "pending",
    descriptorReady: false,
    sourceId: "src-003",
    dataSource: "模拟筛选",
    notes: "芳香胺类抗氧剂候选分子。",
    createdAt: now,
    updatedAt: now
  }
];

const rdkitDescriptor = (molecule: Molecule): Record<string, unknown> => ({
  MolWt: molecule.molecularWeight,
  ExactMolWt: molecule.molecularWeight - 0.024,
  MolLogP: molecule.category === "additive" ? 3.2 : 7.4,
  TPSA: molecule.smilesCanonical.includes("O") ? 46.5 : 0,
  NumHDonors: molecule.smilesCanonical.includes("N") ? 1 : 0,
  NumHAcceptors: (molecule.smilesCanonical.match(/[ONSP]/g) || []).length,
  NumRotatableBonds: molecule.name.includes("十六烷") ? 13 : 4,
  RingCount: molecule.smilesCanonical.includes("c1") ? 2 : 0,
  HeavyAtomCount: Math.round(molecule.molecularWeight / 14),
  FractionCSP3: molecule.category === "additive" ? 0.35 : 1,
  NumAromaticRings: molecule.smilesCanonical.includes("c1") ? 2 : 0,
  NumAliphaticRings: 0,
  NumHeteroatoms: (molecule.smilesCanonical.match(/[ONSPZn]/g) || []).length,
  Element_C: Number((molecule.formula.match(/C(\d+)/) || [0, 1])[1]),
  Element_H: Number((molecule.formula.match(/H(\d+)/) || [0, 0])[1]),
  Element_O: Number((molecule.formula.match(/O(\d*)/) || [0, 0])[1] || 1),
  Element_N: molecule.formula.includes("N") ? Number((molecule.formula.match(/N(\d*)/) || [0, 1])[1] || 1) : 0,
  Element_S: molecule.formula.includes("S") ? Number((molecule.formula.match(/S(\d*)/) || [0, 1])[1] || 1) : 0,
  Element_P: molecule.formula.includes("P") ? Number((molecule.formula.match(/P(\d*)/) || [0, 1])[1] || 1) : 0,
  Element_F: 0,
  Element_Cl: 0,
  Element_Br: 0,
  Element_I: 0,
  Element_B: 0,
  Element_Si: 0,
  Element_Mo: 0,
  Element_Zn: molecule.formula.includes("Zn") ? 1 : 0
});

const mordredDescriptor = (molecule: Molecule): Record<string, unknown> => ({
  ABC: Number((molecule.molecularWeight / 19).toFixed(3)),
  ABCGG: Number((molecule.molecularWeight / 21).toFixed(3)),
  nAtom: Math.round(molecule.molecularWeight / 7),
  ATS0dv: molecule.molecularWeight,
  nAcid: molecule.smilesCanonical.includes("P") ? 1 : 0,
  nBase: molecule.smilesCanonical.includes("N") ? 1 : 0,
  mockWideDescriptor001: Number((molecule.molecularWeight * 0.11).toFixed(3)),
  mockWideDescriptor002: Number((molecule.molecularWeight * 0.17).toFixed(3))
});

export const moleculeDescriptors: MoleculeDescriptor[] = molecules.flatMap((molecule) => [
  {
    id: `${molecule.id}-rdkit`,
    moleculeId: molecule.id,
    descriptorSet: "rdkit",
    descriptorVersion: molecule.rdkitDescriptorStatus === "mock" ? "2026.mock" : "2026.06",
    descriptorsJson: rdkitDescriptor(molecule),
    descriptorCount: Object.keys(rdkitDescriptor(molecule)).length,
    status: molecule.rdkitDescriptorStatus,
    mode: molecule.rdkitDescriptorStatus === "mock" ? "mock" : "real",
    errorMessage: molecule.rdkitDescriptorStatus === "failed" ? "RDKit 计算失败。" : "",
    calculatedAt: now
  },
  {
    id: `${molecule.id}-mordred`,
    moleculeId: molecule.id,
    descriptorSet: "mordred",
    descriptorVersion: molecule.mordredDescriptorStatus === "mock" ? "1.2.0-mock" : "1.2.0",
    descriptorsJson: molecule.mordredDescriptorStatus === "failed" ? {} : mordredDescriptor(molecule),
    descriptorCount: molecule.mordredDescriptorStatus === "failed" ? 0 : Object.keys(mordredDescriptor(molecule)).length,
    status: molecule.mordredDescriptorStatus,
    mode: molecule.mordredDescriptorStatus === "mock" ? "mock" : "real",
    errorMessage:
      molecule.mordredDescriptorStatus === "failed"
        ? "Mordred 描述符为必需项。请安装 Mordred 或检查 Python sidecar 环境。"
        : "",
    calculatedAt: now
  }
]);

export const baseOils: BaseOil[] = [
  {
    id: "bo-001",
    name: "PAO-6",
    baseOilType: "PAO",
    representativeMoleculeId: "mol-002",
    viscosity40c: 31.1,
    viscosity100c: 5.9,
    viscosityIndex: 138,
    density: 0.82,
    pourPoint: -57,
    flashPoint: 230,
    supplier: "模拟供应商 A",
    batchNumber: "PAO6-2026-A",
    formulationCount: 3,
    notes: "合成基础油。",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "bo-002",
    name: "矿物油 SN150",
    baseOilType: "矿物油",
    viscosity40c: 29.2,
    viscosity100c: 5.2,
    viscosityIndex: 101,
    density: 0.87,
    pourPoint: -15,
    flashPoint: 218,
    supplier: "模拟供应商 B",
    batchNumber: "SN150-B",
    formulationCount: 1,
    notes: "可在没有 SMILES 的情况下存在。",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "bo-003",
    name: "酯类油",
    baseOilType: "酯类",
    viscosity40c: 34.5,
    viscosity100c: 6.8,
    viscosityIndex: 151,
    density: 0.93,
    pourPoint: -42,
    flashPoint: 245,
    supplier: "模拟供应商 C",
    batchNumber: "ESTER-C",
    formulationCount: 2,
    notes: "极性基础油候选。",
    createdAt: now,
    updatedAt: now
  }
];

export const additives: Additive[] = [
  {
    id: "add-001",
    moleculeId: "mol-003",
    moleculeName: "类 ZDDP 添加剂",
    functionTypes: ["antiwear", "extreme_pressure"],
    activeElements: ["Zn", "P", "S"],
    typicalConcentrationMin: 0.5,
    typicalConcentrationMax: 1.2,
    concentrationUnit: "wt%",
    compatibleBaseOils: ["PAO-6", "矿物油 SN150"],
    formulationCount: 3,
    bestFrictionCoefficient: 0.082,
    bestWearScarDiameter: 412,
    applicationNotes: "主要抗磨添加剂。",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "add-002",
    moleculeId: "mol-004",
    moleculeName: "磷酸酯添加剂",
    functionTypes: ["antiwear", "friction_modifier"],
    activeElements: ["P", "O"],
    typicalConcentrationMin: 0.2,
    typicalConcentrationMax: 0.8,
    concentrationUnit: "wt%",
    compatibleBaseOils: ["酯类油"],
    formulationCount: 2,
    bestFrictionCoefficient: 0.076,
    bestWearScarDiameter: 390,
    applicationNotes: "模拟状态下 Mordred 失败。",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "add-003",
    moleculeId: "mol-005",
    moleculeName: "胺类抗氧剂",
    functionTypes: ["antioxidant"],
    activeElements: ["N"],
    typicalConcentrationMin: 0.1,
    typicalConcentrationMax: 0.5,
    concentrationUnit: "wt%",
    compatibleBaseOils: ["PAO-6", "酯类油"],
    formulationCount: 1,
    bestFrictionCoefficient: 0.099,
    bestWearScarDiameter: 505,
    applicationNotes: "氧化稳定性改进剂。",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "add-004",
    moleculeId: "mol-002",
    moleculeName: "PAO 代表分子",
    functionTypes: ["viscosity_modifier"],
    activeElements: ["C", "H"],
    typicalConcentrationMin: 1,
    typicalConcentrationMax: 3,
    concentrationUnit: "wt%",
    compatibleBaseOils: ["矿物油 SN150"],
    formulationCount: 1,
    bestFrictionCoefficient: 0.112,
    bestWearScarDiameter: 560,
    applicationNotes: "占位添加剂样式记录。",
    createdAt: now,
    updatedAt: now
  }
];

export const formulations: Formulation[] = [
  {
    id: "frm-001",
    name: "PAO-6 + ZDDP 1.0%",
    baseOil: "PAO-6",
    additiveCount: 1,
    componentsSummary: "PAO-6 99 wt%，类 ZDDP 添加剂 1 wt%",
    preparationMethod: "搅拌",
    preparationTemperature: 60,
    preparationTemperatureUnit: "C",
    preparationTime: 30,
    preparationTimeUnit: "min",
    stabilityObservation: "24 h 后澄清",
    experimentCount: 2,
    bestAverageFrictionCoefficient: 0.082,
    bestWearScarDiameter: 412,
    highestOxidationTemperature: 238,
    notes: "模拟基准配方。",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "frm-002",
    name: "酯类油 + 磷酸酯",
    baseOil: "酯类油",
    additiveCount: 1,
    componentsSummary: "酯类油 99.5 wt%，磷酸酯 0.5 wt%",
    preparationMethod: "超声",
    stabilityObservation: "轻微浑浊",
    experimentCount: 1,
    bestAverageFrictionCoefficient: 0.076,
    bestWearScarDiameter: 390,
    highestOxidationTemperature: 221,
    notes: "",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "frm-003",
    name: "PAO 抗氧剂筛选",
    baseOil: "PAO-6",
    additiveCount: 2,
    componentsSummary: "PAO-6、胺类抗氧剂、类 ZDDP 添加剂",
    preparationMethod: "加热",
    stabilityObservation: "澄清",
    experimentCount: 1,
    bestAverageFrictionCoefficient: 0.091,
    bestWearScarDiameter: 468,
    highestOxidationTemperature: 260,
    notes: "",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "frm-004",
    name: "SN150 探索配方",
    baseOil: "矿物油 SN150",
    additiveCount: 1,
    componentsSummary: "SN150 98 wt%，模拟黏度指数改进剂 2 wt%",
    preparationMethod: "搅拌",
    stabilityObservation: "澄清",
    experimentCount: 1,
    bestAverageFrictionCoefficient: 0.112,
    bestWearScarDiameter: 560,
    highestOxidationTemperature: 205,
    notes: "",
    createdAt: now,
    updatedAt: now
  }
];

export const experiments: Experiment[] = Array.from({ length: 5 }).map((_, index) => ({
  id: `exp-00${index + 1}`,
  formulationId: formulations[index % formulations.length].id,
  formulationName: formulations[index % formulations.length].name,
  testType: ["SRV", "四球试验", "球盘试验", "PDSC", "黏度测试"][index],
  testStandard: `模拟标准 ${index + 1}`,
  instrument: `仪器 ${index + 1}`,
  upperMaterial: "GCr15 钢",
  lowerMaterial: "GCr15 钢",
  loadValue: 100 + index * 20,
  loadUnit: "N",
  temperatureValue: 80 + index * 10,
  temperatureUnit: "C",
  durationValue: 30,
  durationUnit: "min",
  operator: "研究员",
  experimentDate: "2026-06-18",
  notes: "模拟实验条件。",
  createdAt: now,
  updatedAt: now
}));

export const performanceResults: PerformanceResult[] = experiments.map((experiment, index) => ({
  id: `perf-00${index + 1}`,
  experimentId: experiment.id,
  averageFrictionCoefficient: [0.082, 0.076, 0.091, 0.112, 0.099][index],
  stableFrictionCoefficient: [0.078, 0.073, 0.087, 0.109, 0.096][index],
  wearScarDiameterValue: [412, 390, 468, 560, 505][index],
  initialOxidationTemperatureValue: [238, 221, 260, 205, 248][index],
  extremePressureValue: [620, 540, 600, 420, 480][index],
  pbValue: [785, 706, 760, 510, 650][index],
  pdValue: [1960, 1569, 1765, 980, 1372][index],
  viscosity40c: [31.5, 34.9, 32.1, 29.8, 31.9][index],
  viscosity100c: [6.1, 6.9, 6.2, 5.4, 6.0][index],
  repeatCount: 3,
  notes: "模拟性能结果。",
  createdAt: now,
  updatedAt: now
}));

export const dashboardSummary: DashboardSummary = {
  moleculeCount: molecules.length,
  baseOilCount: baseOils.length,
  additiveCount: additives.length,
  formulationCount: formulations.length,
  experimentCount: experiments.length,
  descriptorReadyCount: molecules.filter((item) => item.descriptorReady).length,
  descriptorFailedCount: molecules.filter((item) => item.mordredDescriptorStatus === "failed").length
};
