import type {
  Additive,
  BaseOil,
  DashboardSummary,
  Experiment,
  Formulation,
  Molecule,
  MoleculeDescriptor,
  PerformanceResult
} from "../types";

const now = "2026-06-18T12:00:00.000Z";

export const mockSvg = (label: string) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="420" height="240" viewBox="0 0 420 240"><rect width="420" height="240" rx="6" fill="#f8fafc"/><path d="M80 128 L150 88 L220 128 L290 88 L350 126" stroke="#0f766e" stroke-width="8" fill="none" stroke-linecap="round" stroke-linejoin="round"/><circle cx="80" cy="128" r="18" fill="#2563eb"/><circle cx="150" cy="88" r="18" fill="#14b8a6"/><circle cx="220" cy="128" r="18" fill="#f59e0b"/><circle cx="290" cy="88" r="18" fill="#ef4444"/><circle cx="350" cy="126" r="18" fill="#64748b"/><text x="210" y="206" text-anchor="middle" font-family="Arial" font-size="18" fill="#172033">${label}</text></svg>`;

export const molecules: Molecule[] = [
  {
    id: "mol-001",
    name: "n-Hexadecane",
    aliases: "Hexadecane",
    smilesRaw: "CCCCCCCCCCCCCCCC",
    smilesCanonical: "CCCCCCCCCCCCCCCC",
    inchi: "InChI=1S/C16H34/c1-3-5-7-9-11-13-15-16-14-12-10-8-6-4-2/h3-16H2,1-2H3",
    inchiKey: "DCAYPVUWAIABOU-UHFFFAOYSA-N",
    formula: "C16H34",
    molecularWeight: 226.448,
    category: "base_oil_representative",
    additiveFunctionTags: [],
    structureSvgPath: "files/structures/mol-001.svg",
    structureSvg: mockSvg("n-Hexadecane"),
    molFilePath: "files/structures/mol-001.mol",
    sdfFilePath: "files/structures/mol-001.sdf",
    pdbFilePath: "",
    sdfBlock: "n-Hexadecane\n  LMD Mock\n\n  0  0  0  0  0  0            999 V2000\nM  END\n$$$$",
    rdkitDescriptorStatus: "calculated",
    mordredDescriptorStatus: "calculated",
    descriptorReady: true,
    sourceId: "src-001",
    dataSource: "Mock literature",
    notes: "Representative linear-hydrocarbon base-oil molecule.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "mol-002",
    name: "PAO Representative Molecule",
    aliases: "Hydrogenated polyalphaolefin fragment",
    smilesRaw: "CC(C)CCCC(C)CCCC",
    smilesCanonical: "CC(C)CCCC(C)CCCC",
    inchi: "mock:InChI:PAO",
    inchiKey: "PAOREPRESENTATIVE",
    formula: "C13H28",
    molecularWeight: 184.37,
    category: "base_oil_representative",
    additiveFunctionTags: [],
    structureSvgPath: "files/structures/mol-002.svg",
    structureSvg: mockSvg("PAO Representative Molecule"),
    molFilePath: "",
    sdfFilePath: "",
    pdbFilePath: "",
    rdkitDescriptorStatus: "calculated",
    mordredDescriptorStatus: "mock",
    descriptorReady: true,
    sourceId: "src-001",
    dataSource: "Internal mock data",
    notes: "Mock representative molecule for PAO base oil.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "mol-003",
    name: "ZDDP-like Additive",
    aliases: "Zinc dialkyldithiophosphate analogue",
    smilesRaw: "CCOP(=S)(S[Zn]SP(=S)(OCC)OCC)OCC",
    smilesCanonical: "CCOP(=S)(S[Zn]SP(=S)(OCC)OCC)OCC",
    inchi: "mock:InChI:ZDDP",
    inchiKey: "ZDDPLIKEADDITIVE",
    formula: "C8H20O4P2S4Zn",
    molecularWeight: 419.86,
    category: "additive",
    additiveFunctionTags: ["antiwear", "extreme_pressure"],
    structureSvgPath: "files/structures/mol-003.svg",
    structureSvg: mockSvg("ZDDP-like Additive"),
    molFilePath: "",
    sdfFilePath: "",
    pdbFilePath: "",
    rdkitDescriptorStatus: "calculated",
    mordredDescriptorStatus: "calculated",
    descriptorReady: true,
    sourceId: "src-002",
    dataSource: "Mock additive dataset",
    notes: "Contains Zn, P, and S for antiwear-film formation.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "mol-004",
    name: "Phosphate Ester Additive",
    aliases: "Triaryl phosphate analogue",
    smilesRaw: "O=P(Oc1ccccc1)(Oc1ccccc1)Oc1ccccc1",
    smilesCanonical: "O=P(Oc1ccccc1)(Oc1ccccc1)Oc1ccccc1",
    inchi: "mock:InChI:PhosphateEster",
    inchiKey: "PHOSPHATEESTERMOCK",
    formula: "C18H15O4P",
    molecularWeight: 326.29,
    category: "additive",
    additiveFunctionTags: ["antiwear", "friction_modifier"],
    structureSvgPath: "files/structures/mol-004.svg",
    structureSvg: mockSvg("Phosphate Ester"),
    molFilePath: "",
    sdfFilePath: "",
    pdbFilePath: "",
    rdkitDescriptorStatus: "calculated",
    mordredDescriptorStatus: "failed",
    descriptorReady: false,
    sourceId: "src-003",
    dataSource: "Mock screening",
    notes: "Mordred intentionally fails in mock data to verify Descriptor Center behavior.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "mol-005",
    name: "Amine Antioxidant",
    aliases: "Diphenylamine-like antioxidant",
    smilesRaw: "c1ccc(Nc2ccccc2)cc1",
    smilesCanonical: "c1ccc(Nc2ccccc2)cc1",
    inchi: "mock:InChI:AmineAntioxidant",
    inchiKey: "AMINEANTIOXIDANT",
    formula: "C12H11N",
    molecularWeight: 169.23,
    category: "additive",
    additiveFunctionTags: ["antioxidant"],
    structureSvgPath: "files/structures/mol-005.svg",
    structureSvg: mockSvg("Amine Antioxidant"),
    molFilePath: "",
    sdfFilePath: "",
    pdbFilePath: "",
    rdkitDescriptorStatus: "pending",
    mordredDescriptorStatus: "pending",
    descriptorReady: false,
    sourceId: "src-003",
    dataSource: "Mock screening",
    notes: "Aromatic-amine antioxidant candidate.",
    createdAt: now,
    updatedAt: now
  }
];

const rdkitDescriptor = (molecule: Molecule): Record<string, unknown> => ({
  MolWt: molecule.molecularWeight,
  ExactMolWt: molecule.molecularWeight - 0.024,
  MolLogP: molecule.category === "additive" ? 3.2 : 7.4,
  TPSA: molecule.smilesCanonical.includes("O") ? 46.5 : 0,
  NumHDonors: molecule.smilesCanonical.includes("N") ? 1 : 0,
  NumHAcceptors: (molecule.smilesCanonical.match(/[ONSP]/g) || []).length,
  NumRotatableBonds: molecule.name.includes("Hexadecane") ? 13 : 4,
  RingCount: molecule.smilesCanonical.includes("c1") ? 2 : 0,
  HeavyAtomCount: Math.round(molecule.molecularWeight / 14),
  FractionCSP3: molecule.category === "additive" ? 0.35 : 1,
  NumAromaticRings: molecule.smilesCanonical.includes("c1") ? 2 : 0,
  NumAliphaticRings: 0,
  NumHeteroatoms: (molecule.smilesCanonical.match(/[ONSPZn]/g) || []).length,
  Element_C: Number((molecule.formula.match(/C(\d+)/) || [0, 1])[1]),
  Element_H: Number((molecule.formula.match(/H(\d+)/) || [0, 0])[1]),
  Element_O: Number((molecule.formula.match(/O(\d*)/) || [0, 0])[1] || 1),
  Element_N: molecule.formula.includes("N") ? Number((molecule.formula.match(/N(\d*)/) || [0, 1])[1] || 1) : 0,
  Element_S: molecule.formula.includes("S") ? Number((molecule.formula.match(/S(\d*)/) || [0, 1])[1] || 1) : 0,
  Element_P: molecule.formula.includes("P") ? Number((molecule.formula.match(/P(\d*)/) || [0, 1])[1] || 1) : 0,
  Element_F: 0,
  Element_Cl: 0,
  Element_Br: 0,
  Element_I: 0,
  Element_B: 0,
  Element_Si: 0,
  Element_Mo: 0,
  Element_Zn: molecule.formula.includes("Zn") ? 1 : 0
});

const mordredDescriptor = (molecule: Molecule): Record<string, unknown> => ({
  ABC: Number((molecule.molecularWeight / 19).toFixed(3)),
  ABCGG: Number((molecule.molecularWeight / 21).toFixed(3)),
  nAtom: Math.round(molecule.molecularWeight / 7),
  ATS0dv: molecule.molecularWeight,
  nAcid: molecule.smilesCanonical.includes("P") ? 1 : 0,
  nBase: molecule.smilesCanonical.includes("N") ? 1 : 0,
  mockWideDescriptor001: Number((molecule.molecularWeight * 0.11).toFixed(3)),
  mockWideDescriptor002: Number((molecule.molecularWeight * 0.17).toFixed(3))
});

export const moleculeDescriptors: MoleculeDescriptor[] = molecules.flatMap((molecule) => [
  {
    id: `${molecule.id}-rdkit`,
    moleculeId: molecule.id,
    descriptorSet: "rdkit",
    descriptorVersion: molecule.rdkitDescriptorStatus === "mock" ? "2026.mock" : "2026.06",
    descriptorsJson: rdkitDescriptor(molecule),
    descriptorCount: Object.keys(rdkitDescriptor(molecule)).length,
    status: molecule.rdkitDescriptorStatus,
    mode: molecule.rdkitDescriptorStatus === "mock" ? "mock" : "real",
    errorMessage: molecule.rdkitDescriptorStatus === "failed" ? "RDKit calculation failed." : "",
    calculatedAt: now
  },
  {
    id: `${molecule.id}-mordred`,
    moleculeId: molecule.id,
    descriptorSet: "mordred",
    descriptorVersion: molecule.mordredDescriptorStatus === "mock" ? "1.2.0-mock" : "1.2.0",
    descriptorsJson: molecule.mordredDescriptorStatus === "failed" ? {} : mordredDescriptor(molecule),
    descriptorCount: molecule.mordredDescriptorStatus === "failed" ? 0 : Object.keys(mordredDescriptor(molecule)).length,
    status: molecule.mordredDescriptorStatus,
    mode: molecule.mordredDescriptorStatus === "mock" ? "mock" : "real",
    errorMessage:
      molecule.mordredDescriptorStatus === "failed"
        ? "Mordred descriptors are required. Install Mordred or check the Python sidecar environment."
        : "",
    calculatedAt: now
  }
]);

export const baseOils: BaseOil[] = [
  {
    id: "bo-001",
    name: "PAO-6",
    baseOilType: "PAO",
    representativeMoleculeId: "mol-002",
    viscosity40c: 31.1,
    viscosity100c: 5.9,
    viscosityIndex: 138,
    density: 0.82,
    pourPoint: -57,
    flashPoint: 230,
    supplier: "Mock Supplier A",
    batchNumber: "PAO6-2026-A",
    formulationCount: 3,
    notes: "Synthetic base oil.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "bo-002",
    name: "Mineral Oil SN150",
    baseOilType: "Mineral Oil",
    viscosity40c: 29.2,
    viscosity100c: 5.2,
    viscosityIndex: 101,
    density: 0.87,
    pourPoint: -15,
    flashPoint: 218,
    supplier: "Mock Supplier B",
    batchNumber: "SN150-B",
    formulationCount: 1,
    notes: "May exist without SMILES.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "bo-003",
    name: "Ester Oil",
    baseOilType: "Ester",
    viscosity40c: 34.5,
    viscosity100c: 6.8,
    viscosityIndex: 151,
    density: 0.93,
    pourPoint: -42,
    flashPoint: 245,
    supplier: "Mock Supplier C",
    batchNumber: "ESTER-C",
    formulationCount: 2,
    notes: "Polar base-oil candidate.",
    createdAt: now,
    updatedAt: now
  }
];

export const additives: Additive[] = [
  {
    id: "add-001",
    moleculeId: "mol-003",
    moleculeName: "ZDDP-like Additive",
    functionTypes: ["antiwear", "extreme_pressure"],
    activeElements: ["Zn", "P", "S"],
    typicalConcentrationMin: 0.5,
    typicalConcentrationMax: 1.2,
    concentrationUnit: "wt%",
    compatibleBaseOils: ["PAO-6", "Mineral Oil SN150"],
    formulationCount: 3,
    bestFrictionCoefficient: 0.082,
    bestWearScarDiameter: 412,
    applicationNotes: "Primary antiwear additive.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "add-002",
    moleculeId: "mol-004",
    moleculeName: "Phosphate Ester Additive",
    functionTypes: ["antiwear", "friction_modifier"],
    activeElements: ["P", "O"],
    typicalConcentrationMin: 0.2,
    typicalConcentrationMax: 0.8,
    concentrationUnit: "wt%",
    compatibleBaseOils: ["Ester Oil"],
    formulationCount: 2,
    bestFrictionCoefficient: 0.076,
    bestWearScarDiameter: 390,
    applicationNotes: "Mordred fails in mock mode.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "add-003",
    moleculeId: "mol-005",
    moleculeName: "Amine Antioxidant",
    functionTypes: ["antioxidant"],
    activeElements: ["N"],
    typicalConcentrationMin: 0.1,
    typicalConcentrationMax: 0.5,
    concentrationUnit: "wt%",
    compatibleBaseOils: ["PAO-6", "Ester Oil"],
    formulationCount: 1,
    bestFrictionCoefficient: 0.099,
    bestWearScarDiameter: 505,
    applicationNotes: "Oxidation-stability improver.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "add-004",
    moleculeId: "mol-002",
    moleculeName: "PAO Representative Molecule",
    functionTypes: ["viscosity_modifier"],
    activeElements: ["C", "H"],
    typicalConcentrationMin: 1,
    typicalConcentrationMax: 3,
    concentrationUnit: "wt%",
    compatibleBaseOils: ["Mineral Oil SN150"],
    formulationCount: 1,
    bestFrictionCoefficient: 0.112,
    bestWearScarDiameter: 560,
    applicationNotes: "Placeholder additive-style record.",
    createdAt: now,
    updatedAt: now
  }
];

export const formulations: Formulation[] = [
  {
    id: "frm-001",
    name: "PAO-6 + ZDDP 1.0%",
    baseOil: "PAO-6",
    additiveCount: 1,
    componentsSummary: "PAO-6 99 wt%, ZDDP-like Additive 1 wt%",
    preparationMethod: "Stirring",
    preparationTemperature: 60,
    preparationTemperatureUnit: "C",
    preparationTime: 30,
    preparationTimeUnit: "min",
    stabilityObservation: "Clear after 24 h",
    experimentCount: 2,
    bestAverageFrictionCoefficient: 0.082,
    bestWearScarDiameter: 412,
    highestOxidationTemperature: 238,
    notes: "Mock baseline formulation.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "frm-002",
    name: "Ester Oil + Phosphate Ester",
    baseOil: "Ester Oil",
    additiveCount: 1,
    componentsSummary: "Ester Oil 99.5 wt%, Phosphate Ester 0.5 wt%",
    preparationMethod: "Ultrasonication",
    stabilityObservation: "Slightly cloudy",
    experimentCount: 1,
    bestAverageFrictionCoefficient: 0.076,
    bestWearScarDiameter: 390,
    highestOxidationTemperature: 221,
    notes: "",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "frm-003",
    name: "PAO Antioxidant Screening",
    baseOil: "PAO-6",
    additiveCount: 2,
    componentsSummary: "PAO-6, Amine Antioxidant, ZDDP-like Additive",
    preparationMethod: "Heating",
    stabilityObservation: "Clear",
    experimentCount: 1,
    bestAverageFrictionCoefficient: 0.091,
    bestWearScarDiameter: 468,
    highestOxidationTemperature: 260,
    notes: "",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "frm-004",
    name: "SN150 Exploratory Formulation",
    baseOil: "Mineral Oil SN150",
    additiveCount: 1,
    componentsSummary: "SN150 98 wt%, Mock Viscosity-index Improver 2 wt%",
    preparationMethod: "Stirring",
    stabilityObservation: "Clear",
    experimentCount: 1,
    bestAverageFrictionCoefficient: 0.112,
    bestWearScarDiameter: 560,
    highestOxidationTemperature: 205,
    notes: "",
    createdAt: now,
    updatedAt: now
  }
];

export const experiments: Experiment[] = Array.from({ length: 5 }).map((_, index) => ({
  id: `exp-00${index + 1}`,
  formulationId: formulations[index % formulations.length].id,
  formulationName: formulations[index % formulations.length].name,
  testType: ["SRV", "Four-ball Test", "Ball-on-disk Test", "PDSC", "Viscosity Test"][index],
  testStandard: `Mock Standard ${index + 1}`,
  instrument: `Instrument ${index + 1}`,
  upperMaterial: "GCr15 Steel",
  lowerMaterial: "GCr15 Steel",
  loadValue: 100 + index * 20,
  loadUnit: "N",
  temperatureValue: 80 + index * 10,
  temperatureUnit: "C",
  durationValue: 30,
  durationUnit: "min",
  operator: "Researcher",
  experimentDate: "2026-06-18",
  notes: "Mock experimental conditions.",
  createdAt: now,
  updatedAt: now
}));

export const performanceResults: PerformanceResult[] = experiments.map((experiment, index) => ({
  id: `perf-00${index + 1}`,
  experimentId: experiment.id,
  averageFrictionCoefficient: [0.082, 0.076, 0.091, 0.112, 0.099][index],
  stableFrictionCoefficient: [0.078, 0.073, 0.087, 0.109, 0.096][index],
  wearScarDiameterValue: [412, 390, 468, 560, 505][index],
  initialOxidationTemperatureValue: [238, 221, 260, 205, 248][index],
  extremePressureValue: [620, 540, 600, 420, 480][index],
  pbValue: [785, 706, 760, 510, 650][index],
  pdValue: [1960, 1569, 1765, 980, 1372][index],
  viscosity40c: [31.5, 34.9, 32.1, 29.8, 31.9][index],
  viscosity100c: [6.1, 6.9, 6.2, 5.4, 6.0][index],
  repeatCount: 3,
  notes: "Mock performance result.",
  createdAt: now,
  updatedAt: now
}));

export const dashboardSummary: DashboardSummary = {
  moleculeCount: molecules.length,
  baseOilCount: baseOils.length,
  additiveCount: additives.length,
  formulationCount: formulations.length,
  experimentCount: experiments.length,
  descriptorReadyCount: molecules.filter((item) => item.descriptorReady).length,
  descriptorFailedCount: molecules.filter((item) => item.mordredDescriptorStatus === "failed").length
};
